# Generated by Django 4.0.3 on 2022-04-04 16:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 4, 16, 26, 35, 473699, tzinfo=utc), verbose_name='date added course'),
        ),
    ]
