# Generated by Django 4.0.3 on 2022-04-27 13:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_answer_course_alter_answer_task_alter_answer_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='course',
        ),
        migrations.AlterField(
            model_name='course',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 27, 13, 38, 26, 716619, tzinfo=utc), verbose_name='date added course'),
        ),
    ]
