# Generated by Django 4.0.3 on 2022-05-13 13:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_remove_answer_course_alter_course_date_added'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='text_course',
        ),
        migrations.AddField(
            model_name='course',
            name='file_name',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='course',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 13, 13, 16, 5, 657633, tzinfo=utc), verbose_name='date added course'),
        ),
    ]
