# Generated by Django 4.0.3 on 2022-05-24 10:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_remove_course_text_course_course_file_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='file_name',
        ),
        migrations.RemoveField(
            model_name='course',
            name='img',
        ),
        migrations.AddField(
            model_name='course',
            name='file_course',
            field=models.FileField(default='defaultDocxFile', upload_to='media/docx/'),
        ),
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.ImageField(default='defaultImage', upload_to='media/image/'),
        ),
        migrations.AlterField(
            model_name='course',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 24, 10, 47, 2, 380601, tzinfo=utc), verbose_name='date added course'),
        ),
    ]
