# Generated by Django 4.0.3 on 2022-05-31 10:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_alter_course_date_added_alter_course_file_course_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 31, 10, 28, 45, 895742, tzinfo=utc), verbose_name='date added course'),
        ),
        migrations.AlterField(
            model_name='course',
            name='file_course',
            field=models.FileField(default='defaultDocxFile.docx', upload_to='docx/'),
        ),
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(default='defaultImage.jpg', upload_to='image/'),
        ),
    ]
