# Generated by Django 4.0.3 on 2022-06-02 12:13

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0016_alter_course_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='creator_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='course',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 2, 12, 13, 4, 490991, tzinfo=utc), verbose_name='date added course'),
        ),
    ]
