# Generated by Django 4.0.3 on 2022-06-02 12:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0018_alter_course_creator_id_alter_course_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 2, 12, 15, 42, 329354, tzinfo=utc), verbose_name='date added course'),
        ),
    ]
