# Generated by Django 4.0.3 on 2022-06-02 14:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0019_alter_course_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='creator_id',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='course',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 2, 14, 16, 24, 380162, tzinfo=utc), verbose_name='date added course'),
        ),
    ]
