# Generated by Django 4.0.3 on 2022-06-01 15:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0002_alter_profile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 1, 15, 3, 30, 238652, tzinfo=utc), verbose_name='date added avatar'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='', upload_to='image/avatars/'),
        ),
    ]
