# Generated by Django 4.0.3 on 2022-06-02 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0003_profile_date_alter_profile_avatar'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
